version: 2
updates:
  # python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    ignore:
      # Ignore all updates to dbt and metricflow packages for internal builds
      - dependency-name: "dbt-*"
      - dependency-name: "metricflow*"
      # Manually exclude annoying-to-update dev dependencies
      - dependency-name: "ruff"
      - dependency-name: "pre-commit"
      - dependency-name: "black"
      - dependency-name: "mypy"

  # GitHub actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
