[project]
name = "dbt-semantic-interfaces"
version = "0.1.0"
description = 'The shared semantic layer definitions that dbt-core and MetricFlow use'
readme = "README.md"
requires-python = ">=3.8"
license = "Apache2"
keywords = []
authors = [
  { name = "Callum McCann", email = "cmccann51@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.envs.pre-commit]
description = "Env for running pre-commit hooks."
dependencies = [
  "pre-commit~=3.2.2",
  "isort~=5.12.0",
  "black~=23.3.0",
  "ruff~=0.0.260",
  "mypy~=1.1.1",
  "pytest~=7.3.0",
]

[tool.hatch.envs.pre-commit.scripts]
all = ["pre-commit run --all-files"]

[tool.hatch.envs.pytest]
description = "Env for running pytest."
dependencies = [
  "pytest~=7.3.0",
  "httpx~=0.24.0",
]

[tool.ruff]
line-length = 88
select = [
  "E", # Pycodestyle
  "F", # Pyflakes
  "W", # Whitespace
  "D", # Pydocs
]
ignore = [
  # Missing docstring in public module -- often docs handled within classes
  "D100",
  # Missing docstring in public package -- often docs handled within files not __init__.py
  "D104"
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.mypy]
mypy_path = "third-party-stubs/"
namespace_packages = true
warn_unused_configs = true
disallow_untyped_defs = true
warn_redundant_casts = true

# Don't run the extensive mypy checks on custom stubs
[[tool.mypy.overrides]]
module = ["logbook.*"]
disallow_untyped_defs = false

[tool.isort]
profile = "black"